2025-10-29 18:20:45,943 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:20:46,012 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:21:30,176 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000271175C4790>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:31,689 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027117622190>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:33,899 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027117622DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:35,725 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AACDD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:37,239 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147ADCE10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:39,456 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147ADDC10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:41,132 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AE6750>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:42,644 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AE7790>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:44,857 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AF1110>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:22:29,881 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:22:29,955 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:23:11,897 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:23:11,979 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:26:11,302 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB40F9750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:14,056 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB40E9C90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:17,494 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D1B910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:21,579 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D1CAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:26:24,329 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D195D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:26:27,769 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB410BF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:27:18,964 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020C6D775AD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:27:20,481 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020C6D832050>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:37:29,942 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:37:30,020 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:38:01,503 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:38:01,577 INFO waitress Serving on http://0.0.0.0:8088
