2025-10-29 18:20:45,943 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:20:46,012 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:21:30,176 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000271175C4790>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:31,689 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027117622190>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:33,899 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027117622DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:35,725 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AACDD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:37,239 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147ADCE10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:39,456 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147ADDC10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:41,132 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AE6750>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:42,644 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AE7790>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:21:44,857 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000027147AF1110>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:22:29,881 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:22:29,955 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:23:11,897 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:23:11,979 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:26:11,302 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB40F9750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:14,056 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB40E9C90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:17,494 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D1B910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list_full?token=uTCoBelMyNfSSNmUulT_Kz6zrrCVkvD578MxEuLKZoaaXX0pVlpAD8toYHBxsFxI
2025-10-29 18:26:21,579 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D1CAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:26:24,329 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B82D195D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:26:27,769 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BB410BF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/list
2025-10-29 18:27:18,964 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020C6D775AD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:27:20,481 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020C6D832050>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:37:29,942 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:37:30,020 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:38:01,503 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:38:01,577 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:39:37,599 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:39:37,671 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:40:20,220 WARNING surgibot.surgibot_server [Sheets] Disabled (reason: No valid service account credentials provided. Set SURGIBOT_GCP_CREDENTIALS_JSON or SURGIBOT_GCP_CREDENTIALS_FILE or SURGIBOT_EMBEDDED_CREDENTIALS_JSON.). Running without Sheets.
2025-10-29 18:40:20,293 INFO waitress Serving on http://0.0.0.0:8088
2025-10-29 18:40:49,226 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001991A34DAD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:40:50,742 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001991A3A2190>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:40:52,954 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001991A3A2DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:40:54,814 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A830E10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:40:56,320 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A860DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:40:58,531 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A861CD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:41:00,197 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A86A810>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:41:01,714 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A86B8D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:41:03,916 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001994A8753D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:40,716 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A92104DAD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:42,234 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A9210A2190>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:44,449 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A9210A2DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:46,273 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A951530E10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:47,789 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A951560DD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:50,007 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A951561CD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:51,674 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A95156A810>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:53,187 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A95156B8D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:55,389 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A9515753D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:58,075 WARNING urllib3.connectionpool Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A951561C10>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:45:59,584 WARNING urllib3.connectionpool Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A95156B550>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
2025-10-29 18:46:01,793 WARNING urllib3.connectionpool Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A95156A690>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.8)')': /health
